name: evana_taxi
description: "Taxi application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/