// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiwSa56qkpZFDaS3_DB6NrCwp2uCkEsU',
    appId: '1:921951174709:web:19bf35d6157107e345717c',
    messagingSenderId: '921951174709',
    projectId: 'evana-93d73',
    authDomain: 'evana-93d73.firebaseapp.com',
    databaseURL: 'https://evana-bddfe-default-rtdb.firebaseio.com/',
    storageBucket: 'evana-93d73.firebasestorage.app',
    measurementId: 'G-YDCK5XEF68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpL6YeWcmN73ciic4bqUSPlYqc8g1a3Aw',
    appId: '1:921951174709:android:595123d5653facf045717c',
    messagingSenderId: '921951174709',
    projectId: 'evana-93d73',
    databaseURL: 'https://evana-bddfe-default-rtdb.firebaseio.com/',
    storageBucket: 'evana-93d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDshqPfn2OHx0VWPLbjHjPteJn-wmbaY20',
    appId: '1:921951174709:ios:691ac7b1f0d6f0ad45717c',
    messagingSenderId: '921951174709',
    projectId: 'evana-93d73',
    databaseURL: 'https://evana-bddfe-default-rtdb.firebaseio.com/',
    storageBucket: 'evana-93d73.firebasestorage.app',
    iosClientId:
        '921951174709-vce4je579agve9ke3t20olf68sjva8il.apps.googleusercontent.com',
    iosBundleId: 'evana.com.evanaTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDshqPfn2OHx0VWPLbjHjPteJn-wmbaY20',
    appId: '1:921951174709:ios:691ac7b1f0d6f0ad45717c',
    messagingSenderId: '921951174709',
    projectId: 'evana-93d73',
    databaseURL: 'https://evana-bddfe-default-rtdb.firebaseio.com/',
    storageBucket: 'evana-93d73.firebasestorage.app',
    iosClientId:
        '921951174709-vce4je579agve9ke3t20olf68sjva8il.apps.googleusercontent.com',
    iosBundleId: 'evana.com.evanaTaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkiwSa56qkpZFDaS3_DB6NrCwp2uCkEsU',
    appId: '1:921951174709:web:89fcbd03c215a67545717c',
    messagingSenderId: '921951174709',
    projectId: 'evana-93d73',
    authDomain: 'evana-93d73.firebaseapp.com',
    databaseURL: 'https://evana-bddfe-default-rtdb.firebaseio.com/',
    storageBucket: 'evana-93d73.firebasestorage.app',
    measurementId: 'G-P2KG3HZMBR',
  );
}
